.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,31 +14,39 @@ on:
       - main
 
 jobs:
-  build:
+#  build:
+#    runs-on: 'ubuntu-latest'
+#    steps:
+#      - uses: actions/checkout@v4
+#
+#      - name: Check labels
+#        run: |
+#          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"
+#
+#      - name: Check labelss
+#        run: |
+#          echo "Labels: ${{ toJson(github.event) }}"
+#
+#      - name: Write to Job Summary
+#        run: |
+#          echo "## Job Summary 🚀" >> $GITHUB_STEP_SUMMARY
+#          echo "" >> $GITHUB_STEP_SUMMARY
+#          echo "- ✅ Task 1 completed" >> $GITHUB_STEP_SUMMARY
+#          echo "- ⚠️ Task 2 had warnings" >> $GITHUB_STEP_SUMMARY
+#          echo "- ❌ Task 3 failed" >> $GITHUB_STEP_SUMMARY
+
+  imFailing:
     runs-on: 'ubuntu-latest'
     steps:
-      - uses: actions/checkout@v4
+      - run: exit 1
 
-      - name: Check labels
-        run: |
-          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"
-
-      - name: Check labelss
-        run: |
-          echo "Labels: ${{ toJson(github.event) }}"
-
-      - name: Write to Job Summary
-        run: |
-          echo "## Job Summary 🚀" >> $GITHUB_STEP_SUMMARY
-          echo "" >> $GITHUB_STEP_SUMMARY
-          echo "- ✅ Task 1 completed" >> $GITHUB_STEP_SUMMARY
-          echo "- ⚠️ Task 2 had warnings" >> $GITHUB_STEP_SUMMARY
-          echo "- ❌ Task 3 failed" >> $GITHUB_STEP_SUMMARY
-
+  imSkipped:
+    runs-on: 'ubuntu-latest'
+    needs: ['imFailing']
 
   check:
     runs-on: 'ubuntu-latest'
-    needs: ['build']
+    needs: ['imSkipped']
     steps:
     - run: |
         echo "${{ toJson(needs) }}"
